import { Link } from 'react-router-dom'
import { useState, useEffect } from 'react'
import { 
  Upload, 
  FileText, 
  Activity, 
  Calendar, 
  User,
  LogOut,
  Brain,
  Bell,
  Download,
  Eye,
  CheckCircle,
  AlertTriangle
} from 'lucide-react'
import './PatientDashboard.css'

const PatientDashboard = () => {
  const [treatmentNotifications, setTreatmentNotifications] = useState([])
  const [showNotifications, setShowNotifications] = useState(false)

  useEffect(() => {
    // Load treatment notifications from localStorage
    const treatments = JSON.parse(localStorage.getItem('patientTreatments') || '[]')
    setTreatmentNotifications(treatments)
  }, [])

  const getRiskColor = (level) => {
    switch (level) {
      case 'low': return '#28a745'
      case 'medium': return '#ff8c00'
      case 'high': return '#dc3545'
      default: return '#6c757d'
    }
  }

  const downloadPrescription = (treatment) => {
    // Create a fake prescription document
    const prescriptionContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }
          .header { text-align: center; border-bottom: 2px solid #00ff88; padding-bottom: 20px; margin-bottom: 30px; }
          .patient-info { background: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0; }
          .prescription { border: 1px solid #ddd; padding: 20px; margin: 20px 0; border-radius: 8px; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🏥 City General Hospital</h1>
          <h2>Medical Prescription</h2>
          <p>Endocrinology Department</p>
        </div>
        
        <div class="patient-info">
          <h3>Patient Information</h3>
          <p><strong>Name:</strong> ${treatment.patientName}</p>
          <p><strong>Patient ID:</strong> ${treatment.patientId}</p>
          <p><strong>Date:</strong> ${treatment.submittedDate}</p>
          <p><strong>Follow-up Date:</strong> ${treatment.followUpDate}</p>
        </div>
        
        <div class="prescription">
          <h3>📋 Diagnosis</h3>
          <p>${treatment.diagnosis}</p>
          
          <h3>💊 Prescribed Medications</h3>
          <p>${treatment.medicines}</p>
          
          <h3>🩺 Treatment Instructions</h3>
          <p>${treatment.treatmentDetails}</p>
        </div>
        
        <div class="footer">
          <p>This prescription is generated by AI Health Platform</p>
          <p>Please follow the prescribed treatment plan carefully</p>
          <p>Contact your healthcare provider if you have any questions</p>
        </div>
      </body>
      </html>
    `
    
    const blob = new Blob([prescriptionContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `prescription-${treatment.patientName}-${treatment.submittedDate}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="patient-dashboard">
      <div className="container">
        {/* Header */}
        <div className="dashboard-header">
          <div className="header-content">
            <Brain size={32} />
            <div>
              <h1>Welcome to Your Health Dashboard</h1>
              <p>Manage your health assessments and view AI-powered insights</p>
            </div>
          </div>
          <div className="header-actions">
            {/* Notification Bell */}
            <div className="notification-container">
              <button 
                className="notification-btn"
                onClick={() => setShowNotifications(!showNotifications)}
              >
                <Bell size={24} />
                {treatmentNotifications.length > 0 && (
                  <span className="notification-badge">{treatmentNotifications.length}</span>
                )}
              </button>
              
              {showNotifications && (
                <div className="notification-dropdown">
                  <div className="notification-header">
                    <h3>Treatment Notifications</h3>
                  </div>
                  <div className="notification-list">
                    {treatmentNotifications.length > 0 ? (
                      treatmentNotifications.map((treatment) => (
                        <div key={treatment.id} className="notification-item">
                          <div className="notification-icon">
                            <FileText size={20} />
                          </div>
                          <div className="notification-content">
                            <h4>New Treatment Plan</h4>
                            <p>Treatment plan submitted for {treatment.aiCondition}</p>
                            <span className="notification-date">{treatment.submittedDate}</span>
                          </div>
                          <div className="notification-actions">
                            <button 
                              className="btn-small btn-primary"
                              onClick={() => downloadPrescription(treatment)}
                            >
                              <Download size={14} />
                            </button>
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="no-notifications">
                        <p>No new notifications</p>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
            
            <Link to="/" className="btn btn-secondary">
              <LogOut size={20} />
              Logout
            </Link>
          </div>
        </div>

        {/* Treatment Notifications Section */}
        {treatmentNotifications.length > 0 && (
          <div className="treatment-notifications-section">
            <h2>📧 Recent Treatment Plans</h2>
            <div className="treatment-cards">
              {treatmentNotifications.slice(0, 3).map((treatment) => (
                <div key={treatment.id} className="treatment-card">
                  <div className="treatment-header">
                    <div className="treatment-icon">
                      <FileText size={24} />
                    </div>
                    <div className="treatment-info">
                      <h3>Treatment Plan Received</h3>
                      <p>Submitted on {treatment.submittedDate}</p>
                    </div>
                    <div 
                      className="risk-indicator"
                      style={{ backgroundColor: `${getRiskColor(treatment.riskLevel)}20`, color: getRiskColor(treatment.riskLevel) }}
                    >
                      {treatment.riskLevel.toUpperCase()} RISK
                    </div>
                  </div>
                  
                  <div className="treatment-details">
                    <p><strong>Condition:</strong> {treatment.aiCondition}</p>
                    <p><strong>Diagnosis:</strong> {treatment.diagnosis.substring(0, 100)}...</p>
                    <p><strong>Follow-up:</strong> {treatment.followUpDate}</p>
                  </div>
                  
                  <div className="treatment-actions">
                    <button 
                      className="btn btn-primary"
                      onClick={() => downloadPrescription(treatment)}
                    >
                      <Download size={16} />
                      Download Prescription
                    </button>
                    <Link to="/treatment-copy" className="btn btn-secondary">
                      <Eye size={16} />
                      View Details
                    </Link>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Quick Actions */}
        <div className="quick-actions">
          <h2>Quick Actions</h2>
          <div className="actions-grid">
            <Link to="/patient-upload" className="action-card primary">
              <Upload size={48} />
              <h3>Start Health Assessment</h3>
              <p>Upload lab reports and symptoms for AI analysis</p>
            </Link>
            
            <Link to="/ai-results" className="action-card">
              <Activity size={48} />
              <h3>View Results</h3>
              <p>Check your latest health risk assessments</p>
            </Link>
            
            <Link to="/treatment-copy" className="action-card">
              <FileText size={48} />
              <h3>Treatment History</h3>
              <p>Access your treatment plans and prescriptions</p>
            </Link>
            
            <Link to="/hospital-notification" className="action-card">
              <Calendar size={48} />
              <h3>Appointments</h3>
              <p>View scheduled hospital appointments</p>
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

export default PatientDashboard